<<<<<<< HEAD
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Featured from '../components/featured'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import Login from '../components/login'
import Jumbotron from '../components/jumbotron'
import ProductsCollage from '../components/productsCollage/productsCollage'
import FeaturedProducts from '../components/featuredProducts/featuredProducts'
import LoginModal from '../components/LoginModal'
import { useEffect, useState } from 'react'
import jwt_decode from 'jwt-decode'

const Home: NextPage = () => {
  const [currentUser, setCurrentUser] = useState(null)
  const [showLoginModal, setShowLoginModal] = useState(false)

  useEffect(() => {
    const token = localStorage.getItem('jwt')
    if (token) {
      setCurrentUser(jwt_decode(token))
    } else {
      setCurrentUser(null)
    }
  })

  const handleLogout = () => {
    console.log('log the user out')
    if (localStorage.getItem('jwt')) {
      localStorage.removeItem('jwt')
      setCurrentUser(null)
    }
  }

  const toggleLoginModal = () => {
    setShowLoginModal(prevState => !prevState)
  }

  return (
    <>
      <Head>
        <title>Arondight</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-16x16.png' />
      </Head>
      <LoginModal
        currentUser={currentUser}
        setCurrentUser={setCurrentUser}
        showLoginModal={showLoginModal}
        setShowLoginModal={setShowLoginModal}
        toggleLoginModal={toggleLoginModal}
      />
      <section className='h-fit'>
        <Navbar toggleLoginModal={toggleLoginModal} />
        <Jumbotron />
        <Featured />
      </section>
      <section>
        <ProductsCollage />
      </section>
      <section>
        <FeaturedProducts />
      </section>
    </>
  )
=======
import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Featured from "../components/featured"
import Navbar from "../components/navbar"
import styles from "../styles/Home.module.css"
import Login from "../components/login"
import Jumbotron from "../components/jumbotron"
import ProductsCollage from "../components/productsCollage/productsCollage"
import FeaturedProducts from "../components/featuredProducts/featuredProducts"
import LoginModal from "../components/LoginModal"

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Arondight</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon-16x16.png" />
			</Head>
			<LoginModal />
			<section className="h-fit">
				<Navbar />
				<Jumbotron />
				<Featured />
			</section>
			<section>
				<ProductsCollage />
			</section>
			<section>
				<FeaturedProducts />
			</section>
		</>
	)
>>>>>>> 759a98723dd161e3a989f0034fac9581510a1c76
}

export default Home
