import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Featured from '../components/featured'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import Login from '../components/login'
import Jumbotron from '../components/jumbotron'
import ProductsCollage from '../components/productsCollage/productsCollage'
import FeaturedProducts from '../components/featuredProducts/featuredProducts'
import LoginModal from '../components/LoginModal'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Arondight</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LoginModal />
      <section className='h-fit'>
        <Navbar />
        <Jumbotron />
        <Featured />
      </section>
      <section>
        <ProductsCollage />
      </section>
      <section>
        <FeaturedProducts />
      </section>
    </>
  )
}

export default Home
