import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Featured from '../components/featured'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import Login from '../components/login'
import Jumbotron from '../components/jumbotron'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Arondight</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='h-fit'>
        <Navbar />
        <Jumbotron />
        <Featured />
      </section>
    </>
  )
}

export default Home
